# This was copied from another project
# Base configuration of Test-CZ geometry
crucible:
  h: 0.05  # drawing
  r_in: 0.05  # drawing
  r_out: 0.06  # drawing
  t_bt: 0.01  # drawing
  T_init: 520
  material: graphite-CZ3R6300
crystal:
  l: 0.1  # variable
  r: 0.004  # variable
  T_init: 490
  material: tin-solid
inductor:
  d: 0.01  # construction
  d_in: 0.008  # construction
  g: 0.006  # averaged
  n: 3
  X0: [0.075, -0.005]  # measured
  T_init: 293.15
  material: copper-inductor
insulation:
  r_in: 0.01  # drawing
  r_out: 0.06  # drawing
  h: 0.025  # drawing
  T_init: 450
  material: 'insulation'
melt:
  h: 0.03  # variable
  T_init: 506
  material: tin-liquid
seed:
  r: 0.001  # estimated
  l: 0.04  # estimated
  T_init: 420
  material: tin-solid
surrounding:
  X0: [0, -0.15]
  r: 0.2
  h: 0.45
